config/routes.rb
StackOflow::Application.routes.draw do
  devise_for :users
  root 'welcome#index'

  
  match '/comments',          to: 'comments#index',   via: :get, as: "comments"
  match '/comments',          to: 'comments#create',  via: :post
  match '/comments/new',      to: 'comments#new',     via: :get, as: "new_comment"
  match '/comments/:id/edit', to: 'comments#edit',    via: :get, as: "edit_comment"
  match '/comments/:id',      to: 'comments#show',    via: :get, as: "comment"
  match '/comments/:id',      to: 'comments#update',  via: :patch
  match '/commetns/:id',      to: 'comments#destroy', via: :delete

  resources :questions do
    resources :answers
  end

  match "search", to: "questions#search", via: :post

  match "/votes/question/upvote/:id",   to: "questions#create_up_vote",   via: :get, as: "new_question_upvote"
  match "/votes/question/downvote/:id", to: "questions#create_down_vote", via: :get, as: "new_question_downvote"

  match "/votes/answer/upvote/:id",   to: "answers#create_up_vote",   via: :get, as: "new_answer_upvote"
  match "/votes/answer/downvote/:id", to: "answers#create_down_vote", via: :get, as: "new_answer_downvote"
  match "/top_users", to: "welcome#top_users", via: :get, as: "top_users"
  match "/user", to: "welcome#user", via: :get, as: "user"

  match "/questions/:question_id/mark_as_best/:answer_id", to: "questions#mark_as_best", via: :get, as: "mark_as_best"

  resources :votes

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :answers
  has_many :votes, as: :voteable
  # CODE REVIEW: per other review, this is confusing
  has_one :visit, as: :visitable

  validates :title, presence: true
  validates :body, presence: true
  validates_length_of :title, :minimum => 5, :allow_blank => false
  validates_length_of :body, :minimum => 5, :allow_blank => false

  # scope :popular,
  #   select("questions.title, count(visits.unique_visits) as visits_count").
  #   joins(:visits).
  #   group("questions.title").
  #   order("visits_count DESC").

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include VotesHelper

  before_filter :authenticate_user!, only: [:new]

  def index
    # CODE REVIEW: This is REALLY confusing. My initial reaction was that this
    # should be (at a minumum):
    # Question.all.sort_by! { |question| question.visits.count }
    # But it turns out that Visit is a has_one association from Question. What
    # is actually happening here? If this is actually a has_many (like it looks)
    # then this sorting should be able to be done in the DB
    @questions = Question.all.sort_by! { |question| Visit.where(visitable_id: question.id).count }
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      flash[:notice] = "Question added!"
      redirect_to @question
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    # CODE REVIEW: why not just call vote_total(@question) in the view?
    @question_count = vote_total(@question)
    Visit.track(@question, request.remote_ip)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.user.vote_points -= 1
    @question.user.save
    @question.delete
    redirect_to root_path
  end

  def create_up_vote
    @question = Question.find(params[:id])
    if @question.votes.where(user_id: current_user.id).empty?
      @question.votes.create(user_id: current_user.id, vote_direction: true)
      # CODE REVIEW: There's an AR method that can increment counter cache
      # columns
      @question.user.vote_points += 1
      @question.user.save
    end

    redirect_to @question
  end

  def create_down_vote
    @question = Question.find(params[:id])
    if @question.votes.where(user_id: current_user.id).empty?
      @question.votes.create(user_id: current_user.id, vote_direction: false)
      @question.user.vote_points -= 1
      @question.user.save
    end
    redirect_to @question
  end

  def search
    @search_content = params[:search_data]
    @questions = Question.where("title ILIKE (?)", "%#{@search_content}%")
  end



  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h1>Browse Popular Questions</h1>
<% @questions.each do |question| %>
  <div><%= link_to question.title, question %></div>

<% end %>

app/views/questions/new.html.erb
<h1>Ask a question</h1>

<%= render "questions/form" %>

app/views/questions/search.html.erb
<h1>Search Results</h1>

<h2>Questions</h2>

<% @questions.each do |question| %>
  <div><%= link_to question.title, question %></div>
<% end %>

app/views/questions/show.html.erb
<%# 
  CODE REVIEW: This view could benefit from some partials. It's really hard
  to take it all and a see really what's happening here
%>

<div class="row">
  <div class="col-xs-11">
    <h1><%= @question.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-1">
    <% if current_user %>
      <div class="voting">
        <%# 
          CODE REVIEW: I think link_to can take a block which would (I think)
          would solve your html_safe problem
        %>
        <%= link_to "<span class='glyphicon glyphicon-arrow-up'></span>".html_safe, new_question_upvote_path(@question.id) %>
          <p><%= @question_count %></p>
        <%= link_to "<span class='glyphicon glyphicon-arrow-down'></span>".html_safe, new_question_downvote_path(@question.id) %>
      </div>
    <% else %>
      <div class="voting">
        <%= link_to "<span class='glyphicon glyphicon-arrow-up'></span>".html_safe, new_user_registration_path %>
          <p><%= @question_count %></p>
        <%= link_to "<span class='glyphicon glyphicon-arrow-down'></span>".html_safe, new_user_registration_path %>
      </div>
    <% end %>
  </div>

  <div class="col-xs-9">
    <p><%= markdown @question.body %></p>

    <% @question.comments.each do |comment| %>
      <p><%= comment.body %></p>
      <p>Username: <%= comment.user.username %></p>
    <% end %>
  </div>

  <div class="col-xs-2">
    <h4>Visits</h4>
    <p>Total: <%= @question.visit.total_visits rescue 0 %></p>
    <p>Unique: <%= @question.visit.unique_visits rescue 0 %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% if current_user %>
      <% if current_user.id == @question.user_id %>
        <%= link_to "Delete Question", question_path(@question), method: "delete" %>
      <% end %>
      <%= link_to "Add Comment", new_comment_path(question_id: @question.id) %>
    <% end %>
  </div>
</div>

<% if !@question.answers.empty? %>
  <h3><%= @question.answers.count %> Answers</h3>
  <% @question.answers.each do |answer| %>

  <div class="row">
    <div class="col-xs-1">
      <% if current_user %>
        <div class="voting">
          <%= link_to "<span class='glyphicon glyphicon-arrow-up'></span>".html_safe, new_answer_upvote_path(answer.id) %>
            <p><%= vote_total(answer) %></p>
          <%= link_to "<span class='glyphicon glyphicon-arrow-down'></span>".html_safe, new_answer_downvote_path(answer.id) %>
        </div>
      <% else %>
        <div class="voting">
          <%= link_to "<span class='glyphicon glyphicon-arrow-up'></span>".html_safe, new_user_registration_path %>
            <p><%= @question_count %></p>
          <%= link_to "<span class='glyphicon glyphicon-arrow-down'></span>".html_safe, new_user_registration_path %>
        </div>
      <% end %>
    </div>

    <div class="col-xs-10">
      <div><%= markdown answer.body %></div>
      <div>Username: <%= answer.user.username %></div>

      <div class="comments">
        <% answer.comments.each do |comment| %>
          <p><%= comment.body %></p>
          <p><%= comment.user.username %></p>
        <% end %> 

        <% if current_user %>
          <%= link_to "Add Comment", new_comment_path(answer_id: answer.id) %>
        <% end %>
      </div>
    </div>
  </div>

  <% end %>
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% if current_user %>
      <h2>Answer Question</h2>

      <%= form_for [@question, @answer] do |f| %>
        <%= f.label :body %> <br>
        <%= f.text_area :body, rows: 10, cols: 100 %> <br>
        <%= f.submit %>
      <% end %>
    <% end %>
  </div>
</div>