config/routes.rb
StackOflow::Application.routes.draw do
  devise_for :users
  root 'welcome#index'

  
  match '/comments',          to: 'comments#index',   via: :get, as: "comments"
  match '/comments',          to: 'comments#create',  via: :post
  match '/comments/new',      to: 'comments#new',     via: :get, as: "new_comment"
  match '/comments/:id/edit', to: 'comments#edit',    via: :get, as: "edit_comment"
  match '/comments/:id',      to: 'comments#show',    via: :get, as: "comment"
  match '/comments/:id',      to: 'comments#update',  via: :patch
  match '/commetns/:id',      to: 'comments#destroy', via: :delete

  resources :questions do
    resources :answers
  end

  match "search", to: "questions#search", via: :post

  match "/votes/question/upvote/:id",   to: "questions#create_up_vote",   via: :get, as: "new_question_upvote"
  match "/votes/question/downvote/:id", to: "questions#create_down_vote", via: :get, as: "new_question_downvote"

  match "/votes/answer/upvote/:id",   to: "answers#create_up_vote",   via: :get, as: "new_answer_upvote"
  match "/votes/answer/downvote/:id", to: "answers#create_down_vote", via: :get, as: "new_answer_downvote"
  match "/top_users", to: "welcome#top_users", via: :get, as: "top_users"
  match "/user", to: "welcome#user", via: :get, as: "user"

  match "/questions/:question_id/mark_as_best/:answer_id", to: "questions#mark_as_best", via: :get, as: "mark_as_best"

  resources :votes

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Fox Overflow", root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <li><%= link_to "Ask Question", new_question_path %></li>
          <li><%= link_to "Popular Questions", questions_path %></li>
          <li><%= link_to "Top Users", top_users_path %></li>
      </ul>
      <%= form_for :search, url: search_path, method: :post, html: {class: "navbar-form navbar-left", role: "search"} do |f| %>
        <div class="form-group">
          <%= f.search_field :search, name: "search_data", placeholder: "Search Questions", class: "form-control" %>
          <%= f.button type: :submit, class: "btn btn-primary", value: "Search" %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Public Profile (#{current_user.vote_points})", user_path(current_user.id) %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOflow</title>
  <%= stylesheet_link_tag    "dragon_font/stylesheet.css", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav_bar' %>
	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</div>
</body>
</html>